export const environment = {
     production: true,
     apiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-user/api/v1',
     complaintsIncidentsApiUrl: 'https://vg-ms-claims-incidents-production.up.railway.app/api/v1',
     organizations: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/v1/organizations',
     distribution: 'https://didactic-enigma-5gpxv7g4w4x7f446j-8086.app.github.dev/api/v2',
     testingPoint: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/v2/testingpoints',
     dailyRecords: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/v2/dailyrecords',
     zonas: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/v1/zones',
     street: 'https://lab.vallegrande.edu.pe/jass/ms-organization/api/v1/streets',
     qualityTest: 'https://lab.vallegrande.edu.pe/jass/ms-water-quality/api/v2/qualitytests',
     users: 'https://lab.vallegrande.edu.pe/jass/ms-user/api/v1/api/v1/users/all',
     incidents: 'https://vg-ms-claims-production.up.railway.app/api/v1',
     inventoryApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-inventory/api/v1/',
     infrastructureApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-infrastructure/api/v1/',
     reniecApiUrl: 'https://lab.vallegrande.edu.pe/jass/ms-user/api/v1/users/reniec/dni',
};
